### ISSUE TITLE
Seed for escrow_xdr_transactions table 🌱 

### ISSUE THREAD

**Issue by diegoTech14** [safetrustcr/Backend#49]
## Objective
Create a comprehensive seed script for the escrow_xdr_transactions table with realistic test data.

### Requirements

- Generate seed data that covers various scenarios
- Include different transaction types and statuses
- Reference existing users and bid requests

### Implementation Checklist

- [ ] Write SQL seed script
- [ ] Verify foreign key constraints
- [ ] Ensure data diversity
- [ ] Test seed script for consistency

### Considerations

1. Use uuid_generate_v4() for ID generation
2. Reference existing users and bid_requests IDs
3. Populate all relevant columns

### SQL Table
``` sql

escrow_xdr_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    escrow_transaction_id UUID REFERENCES escrow_transactions(id) ON DELETE CASCADE,
    xdr_type escrow_transaction_type NOT NULL,
    unsigned_xdr TEXT NOT NULL,
    signed_xdr TEXT,
    status xdr_status DEFAULT 'PENDING',
    signing_address TEXT,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

```

### Acceptance criteria
A complete SQL seed script for escrow_xdr_transactions table

**Comment by abdegenius** [comment]
I'd love to work on this!

**Comment by jsanchez556** [comment]
Hi, I am Jose Mario, with over 15 out of the 15 years as a Full Stack Software Developer, I have had the privilege of building and delivering complete, scalable, and cutomer optimized solutions. This has facilitated my proficiency in an array of modern day technologies such as JavaScript, TypeScript, Go, Python, Node.js, React, and C#. Apart from development, I am involved in the database design as well as the optimization of systems, having worked with over SQL Servers, PostgreSQL, MySQL, MongoDB, ElasticSearch, and many more.
Since version 7.0, I’ve actively participated in ODHacks, driven by my work with Dojo Coding, which has sharpened my ability to tackle complex challenges collaboratively.

How to tackle the solution: 

1. Cover all bid_status values, various price ranges according to apartment types, and realistic move-in dates
2. Then use uuid_generate_v4() for the IDs, complete correct foreign key relationships, compute all the prices, and generate timestamps where created_at < updated_at.
3. Test foreign key constraints with apartments and users, ensure data diversity across all statuses, and confirm price and timestamp consistency.
4. Test script output in a development database to ensure complete, realistic, and consistent test data.

**Comment by kallis312** [comment]
I'd like to take this issue.

**Comment by psychemist** [comment]
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience testing backend systems and smart contracts using Jest, Mocha, Chai, and Forge. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I would generate a comprehensive seed script for the escrow_xdr_transactions table by:

- Fetching existing users and escrow transactions IDs from the database to ensure valid foreign key references.
- Using a Python script to generate diverse test data with varying transaction types, statuses but conforming to the class outlined in the requirements
- Generating UUIDs for unique IDs and Faker for timestamps to simulate real-world scenarios.
- Outputting the data as an SQL seed script with 50+ records for testing.
- Verifying the script by testing foreign key constraints and data consistency in my local environment.
- Ensuring the script can be run repeatedly without errors and in a remote environment.

I aim to complete this task within 1 day of being assigned and setting up my development environment.

Thank you for the opportunity and I look forward to working with you.

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by Nityam573** [comment]
Let me try this one!

**Comment by TheSQLguy** [comment]
I am new to open-source
To address this issue, I would Develop a SQL seed script for the escrow_xdr_transactions table using uuid_generate_v4() to generate IDs and referencing valid escrow_transaction_id. Generate diversified data with different types of transactions and statuses and realistic XDR values. Ensure that it has foreign key constraints and data diversification, and test it repeatedly for consistency before submission.

**Comment by ikezuby2012** [comment]
Can I jump on this task?

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando Molina, a full-stack software developer with 2 years of experience. I have worked with languages such as Java, JavaScript, TypeScript, MySQL, C#, and Python. I’m very interested in working on and learning more about this topic.

**Comment by diegoTech14** [comment]
Hi @abdegenius just assigned to you, don't hesitate if you have any question! 🚀

**Comment by abdegenius** [comment]
@diegoTech14 i was about to jump on this, cant run the project on my local machine been trying to fix up some docker blockers with little luck!

**Comment by diegoTech14** [comment]
Hello sir, can you dm me to support you please?

My TG: https://t.me/diegotech1499

**Comment by diegoTech14** [comment]
@abdegenius hello ser, any updates?

**Comment by jsanchez556** [comment]
Thanks for the opportunity, working on it... @diegoTech14
